BTCPayServer.Plugins.LNbank/Controllers/API/WalletsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Client;
using BTCPayServer.Data;
using BTCPayServer.Plugins.LNbank.Authentication;
using BTCPayServer.Plugins.LNbank.Data.API;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WalletData = BTCPayServer.Plugins.LNbank.Data.API.WalletData;

namespace BTCPayServer.Plugins.LNbank.Controllers.API;

[ApiController]
[Route("~/api/v1/lnbank/[controller]")]
[Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield)]
public class WalletsController : ControllerBase
{
    private readonly WalletRepository _walletRepository;
    private readonly UserManager<ApplicationUser> _userManager;

    public WalletsController(UserManager<ApplicationUser> userManager, WalletRepository walletRepository)
    {
        _userManager = userManager;
        _walletRepository = walletRepository;
    }

    [HttpGet("")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield, Policy = Policies.CanModifyProfile)]
    public async Task<IActionResult> GetWallets()
    {
        var wallets = await _walletRepository.GetWallets(new WalletsQuery
        {
            UserId = new[] { GetUserId() },
            IncludeTransactions = true
        });

        return Ok(wallets.Select(FromModel));
    }

    [HttpPost("")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield, Policy = Policies.CanModifyProfile)]
    public async Task<IActionResult> CreateWallet(EditWalletRequest request)
    {
        var validationResult = Validate(request);
        if (validationResult != null)
        {
            return validationResult;
        }

        var wallet = new Wallet
        {
            UserId = GetUserId(),
            Name = request.Name
        };

        var entry = await _walletRepository.AddOrUpdateWallet(wallet);

        return Ok(FromModel(entry));
    }

    [HttpGet("{walletId}")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield, Policy = LNbankPolicies.CanViewWallet)]
    public async Task<IActionResult> GetWallet(string walletId)
    {
        var wallet = await FetchWallet(walletId);
        return wallet == null
            ? this.CreateAPIError(404, "wallet-not-found", "The wallet was not found")
            : Ok(FromModel(wallet));
    }

    [HttpPut("{walletId}")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield, Policy = LNbankPolicies.CanManageWallet)]
    public async Task<IActionResult> UpdateWallet(string walletId, EditWalletRequest request)
    {
        var validationResult = Validate(request);
        if (validationResult != null)
        {
            return validationResult;
        }

        var wallet = await _walletRepository.GetWallet(new WalletsQuery
        {
            UserId = new[] { GetUserId() },
            WalletId = new[] { walletId },
            IncludeTransactions = true,
            IncludeAccessKeys = true
        });

        if (wallet == null)
            return this.CreateAPIError(404, "wallet-not-found", "The wallet was not found");

        wallet.Name = request.Name;

        var entry = await _walletRepository.AddOrUpdateWallet(wallet);

        return Ok(FromModel(entry));
    }

    [HttpDelete("{walletId}")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Greenfield, Policy = LNbankPolicies.CanManageWallet)]
    public async Task<IActionResult> DeleteWallet(string walletId)
    {
        var wallet = await FetchWallet(walletId);
        if (wallet == null)
            return this.CreateAPIError(404, "wallet-not-found", "The wallet was not found");

        try
        {
            await _walletRepository.RemoveWallet(wallet);
            return Ok();
        }
        catch (Exception e)
        {
            return this.CreateAPIError("wallet-not-empty", e.Message);
        }
    }

    private async Task<Wallet> FetchWallet(string walletId) =>
        await _walletRepository.GetWallet(new WalletsQuery
        {
            UserId = new[] { GetUserId() },
            WalletId = new[] { walletId },
            IncludeTransactions = true
        });

    private IActionResult Validate(EditWalletRequest request)
    {
        if (request is null)
        {
            return BadRequest();
        }

        if (string.IsNullOrEmpty(request.Name))
            ModelState.AddModelError(nameof(request.Name), "Name is missing");
        else if (request.Name.Length is < 1 or > 50)
            ModelState.AddModelError(nameof(request.Name), "Name can only be between 1 and 50 characters");

        return !ModelState.IsValid ? this.CreateValidationError(ModelState) : null;
    }

    private WalletData FromModel(Wallet model) =>
        new()
        {
            Id = model.WalletId,
            Name = model.Name,
            CreatedAt = model.CreatedAt,
            Balance = model.Balance,
            AccessKey = model.AccessKeys.FirstOrDefault(ak => ak.UserId == GetUserId())?.Key
        };

    private string GetUserId() => _userManager.GetUserId(User);
}

BTCPayServer.Plugins.LNbank/Controllers/ExportController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Client;
using BTCPayServer.Lightning;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BTCPayServer.Plugins.LNbank.Controllers;

[Route("~/plugins/lnbank/[controller]")]
public class ExportController : Controller
{
    private readonly WalletRepository _walletRepository;

    public ExportController(WalletRepository walletRepository)
    {
        _walletRepository = walletRepository;
    }

    [HttpGet("{walletId}/{format}")]
    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanViewInvoices)]
    public async Task<IActionResult> Export(string walletId, string format)
    {
        var wallet = await _walletRepository.GetWallet(new WalletsQuery { WalletId = new[] { walletId }, IncludeTransactions = true });
        if (wallet == null)
        {
            return NotFound();
        }

        var transactions = wallet.Transactions.Select(ToExportModel);
        var data = format switch
        {
            "json" => ToJson(transactions),
            "csv" => await ToCsv(transactions),
            _ => throw new NotSupportedException("Unsupported format.")
        };

        var cd = new ContentDisposition
        {
            FileName = $"lnbank-export-{DateTime.UtcNow.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture)}-{wallet.WalletId}.{format}",
            Inline = true
        };
        Response.Headers.Add("Content-Disposition", cd.ToString());
        Response.Headers.Add("X-Content-Type-Options", "nosniff");

        return Content(data, $"application/{format}");
    }

    private static string ToJson(IEnumerable<ExportModel> transactions)
    {
        var settings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };
        return JsonConvert.SerializeObject(transactions, Formatting.Indented, settings);
    }

    private static async Task<string> ToCsv(IEnumerable<ExportModel> transactions)
    {
        await using StringWriter writer = new();
        await using var csvWriter = new CsvHelper.CsvWriter(writer, CultureInfo.InvariantCulture, true);
        csvWriter.WriteHeader<ExportModel>();
        await csvWriter.NextRecordAsync();
        await csvWriter.WriteRecordsAsync(transactions);
        await csvWriter.FlushAsync();
        return writer.ToString();
    }

    private static ExportModel ToExportModel(Transaction t) => new()
    {
        TransactionId = t.TransactionId,
        InvoiceId = t.InvoiceId,
        Description = t.Description,
        PaymentRequest = t.PaymentRequest,
        Status = t.Status,
        Amount = t.Amount?.MilliSatoshi,
        AmountSettled = t.AmountSettled?.MilliSatoshi,
        RoutingFee = t.RoutingFee?.MilliSatoshi,
        CreatedAt = t.CreatedAt,
        PaidAt = t.PaidAt
    };

    private class ExportModel
    {
        public string TransactionId { get; set; }
        public string InvoiceId { get; set; }
        public string Description { get; set; }
        public string PaymentRequest { get; set; }
        public string Status { get; set; }
        public long? Amount { get; set; }
        public long? AmountSettled { get; set; }
        public long? RoutingFee { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? PaidAt { get; set; }
    }
}

BTCPayServer.Plugins.LNbank/Pages/Transactions/Details.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Data;
using BTCPayServer.Plugins.LNbank.Authentication;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BTCPayServer.Plugins.LNbank.Pages.Transactions;

[Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = LNbankPolicies.CanViewWallet)]
public class DetailsModel : BasePageModel
{
    public Wallet Wallet { get; set; }
    public Transaction Transaction { get; set; }

    public DetailsModel(
        UserManager<ApplicationUser> userManager,
        WalletRepository walletRepository,
        WalletService walletService) : base(userManager, walletRepository, walletService) { }

    public async Task<IActionResult> OnGetAsync(string walletId, string transactionId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        Transaction = Wallet.Transactions.FirstOrDefault(t => t.TransactionId == transactionId);

        if (Transaction == null)
            return NotFound();

        return Page();
    }
}

BTCPayServer.Plugins.LNbank/Pages/Transactions/Edit.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Data;
using BTCPayServer.Plugins.LNbank.Authentication;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BTCPayServer.Plugins.LNbank.Pages.Transactions;

[Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = LNbankPolicies.CanManageWallet)]
public class EditModel : BasePageModel
{
    public Wallet Wallet { get; set; }
    public Transaction Transaction { get; set; }

    public EditModel(
        UserManager<ApplicationUser> userManager,
        WalletRepository walletRepository,
        WalletService walletService) : base(userManager, walletRepository, walletService) { }

    public async Task<IActionResult> OnGetAsync(string walletId, string transactionId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        Transaction = Wallet.Transactions.FirstOrDefault(t => t.TransactionId == transactionId);

        if (Transaction == null)
            return NotFound();

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(string walletId, string transactionId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        Transaction = await WalletRepository.GetTransaction(new TransactionQuery
        {
            UserId = UserId,
            WalletId = Wallet.WalletId,
            TransactionId = transactionId
        });

        if (!ModelState.IsValid)
            return Page();
        if (Transaction == null)
            return NotFound();

        if (await TryUpdateModelAsync(Transaction, "transaction", t => t.Description))
        {
            await WalletRepository.UpdateTransaction(Transaction);
            return RedirectToPage("/Wallets/Wallet", new { Wallet.WalletId });
        }

        return Page();
    }
}

BTCPayServer.Plugins.LNbank/Pages/Wallets/AccessKeys.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Data;
using BTCPayServer.Plugins.LNbank.Authentication;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AuthenticationSchemes = BTCPayServer.Abstractions.Constants.AuthenticationSchemes;

namespace BTCPayServer.Plugins.LNbank.Pages.Wallets;

[Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = LNbankPolicies.CanManageWallet)]
public class AccessKeysModel : BasePageModel
{
    public Wallet Wallet { get; set; }

    [BindProperty]
    public AccessKeyViewModel AccessKey { get; set; }
    public List<AccessKeyViewModel> AccessKeys { get; set; }

    public class AccessKeyViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string Key { get; set; }
        public AccessLevel Level { get; set; } = AccessLevel.ReadOnly;
    }

    public AccessKeysModel(
        UserManager<ApplicationUser> userManager,
        WalletRepository walletRepository,
        WalletService walletService) : base(userManager, walletRepository, walletService) { }

    public async Task<IActionResult> OnGetAsync(string walletId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        AccessKeys = await GetAccessKeyVMs(Wallet.AccessKeys);

        return Page();
    }

    public async Task<IActionResult> OnPostAddAsync(string walletId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        AccessKeys = await GetAccessKeyVMs(Wallet.AccessKeys);
        if (!ModelState.IsValid)
            return Page();

        var user = await UserManager.FindByEmailAsync(AccessKey.Email);
        if (user == null)
        {
            ModelState.AddModelError(nameof(AccessKey.Email), "User not found");
            return Page();
        }

        if (!Enum.IsDefined(AccessKey.Level))
        {
            ModelState.AddModelError(nameof(AccessKey.Level), "Invalid access level");
            return Page();
        }

        await WalletRepository.AddOrUpdateAccessKey(Wallet.WalletId, user.Id, AccessKey.Level);
        TempData[WellKnownTempData.SuccessMessage] = "Access key added successfully.";
        return RedirectToPage("./AccessKeys", new { walletId });
    }

    public async Task<IActionResult> OnPostRemoveAsync(string walletId, string key)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        try
        {
            await WalletRepository.DeleteAccessKey(Wallet.WalletId, key);

            TempData[WellKnownTempData.SuccessMessage] = "Access key removed successfully.";
            return RedirectToPage("./AccessKeys", new { walletId });
        }
        catch (Exception)
        {
            TempData[WellKnownTempData.ErrorMessage] = "Failed to remove user.";
        }

        AccessKeys = await GetAccessKeyVMs(Wallet.AccessKeys);
        return Page();
    }

    private async Task<List<AccessKeyViewModel>> GetAccessKeyVMs(ICollection<AccessKey> accessKeys)
    {
        var list = new List<AccessKeyViewModel>();
        foreach (var accessKey in accessKeys)
        {
            var user = await UserManager.FindByIdAsync(accessKey.UserId);
            list.Add(new AccessKeyViewModel
            {
                Key = accessKey.Key,
                Email = user.Email,
                Level = accessKey.Level
            });
        }
        return list;
    }
}

BTCPayServer.Plugins.LNbank/Pages/Wallets/Details.cshtml.cs
using System.Threading.Tasks;
using BTCPayServer.Data;
using BTCPayServer.Plugins.LNbank.Authentication;
using BTCPayServer.Plugins.LNbank.Data.Models;
using BTCPayServer.Plugins.LNbank.Services.Wallets;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AuthenticationSchemes = BTCPayServer.Abstractions.Constants.AuthenticationSchemes;

namespace BTCPayServer.Plugins.LNbank.Pages.Wallets;

[Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = LNbankPolicies.CanManageWallet)]
public class DetailsModel : BasePageModel
{
    public Wallet Wallet { get; set; }

    public DetailsModel(
        UserManager<ApplicationUser> userManager,
        WalletRepository walletRepository,
        WalletService walletService) : base(userManager, walletRepository, walletService) { }

    public async Task<IActionResult> OnGetAsync(string walletId)
    {
        Wallet = await GetWallet(UserId, walletId);
        if (Wallet == null)
            return NotFound();

        return Page();
    }
}

BTCPayServer.Plugins.LNbank/Pages/Wallets/AccessKeys.cshtml
@page "/plugins/lnbank/wallets/{walletId}/access-keys/{handler?}"
@using BTCPayServer.Plugins.LNbank.Data.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using BTCPayServer.Abstractions.Models
@using BTCPayServer.Plugins.LNbank.Extensions
@model BTCPayServer.Plugins.LNbank.Pages.Wallets.AccessKeysModel

@{
    ViewData.SetActivePage(LNbankNavPages.WalletAccessKeys, $"Access keys for \"{Model.Wallet.Name}\"", Model.Wallet.WalletId);
    var accessLevelOptions = new SelectList(typeof(AccessLevel).GetEnumNames().Select(o => 
        new SelectListItem(typeof(AccessLevel).DisplayName(o), o)), 
        nameof(SelectListItem.Value), nameof(SelectListItem.Text), Model.AccessKey?.Level);
}

@section LNbankFoot {
    <partial name="_ValidationScriptsPartial" />
}

<partial name="_WalletHeader" model="Model.Wallet"/>
<partial name="_Nav" model="Model.Wallet"/>

<div class="row">
    <div class="col-xxl-constrain">
        <p>Give other registered BTCPay Server users access to your wallet.</p>

        @if (!ViewContext.ModelState.IsValid)
        {
            <div asp-validation-summary="All" class="text-danger"></div>
        }

        <form method="post" asp-page-handler="add">
            <div class="d-flex flex-wrap gap-3">
                <div class="flex-grow-1">
                    <input asp-for="AccessKey.Email" type="text" class="form-control" placeholder="user@example.com">
                    <span asp-validation-for="AccessKey.Email" class="text-danger"></span>
                </div>
                <div>
                    <select asp-for="AccessKey.Level" asp-items="@accessLevelOptions" class="form-select"></select>
                </div>
                <div>
                    <button type="submit" role="button" class="btn btn-primary" id="LNbank-CreateAccessKey">Create Access Key</button>
                </div>
            </div>
        </form>

        @if (Model.AccessKeys.Any())
        {
            <div class="table-responsive" id="LNbank-AccessKeys">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Key</th>
                        <th>Level</th>
                        <th class="text-end">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var accessKey in Model.AccessKeys)
                    {
                        <tr>
                            <td>@accessKey.Email</td>
                            <td>@accessKey.Key</td>
                            <td>@typeof(AccessLevel).DisplayName(accessKey.Level.ToString())</td>
                            <td class="text-end">
                                <a asp-page-handler="remove" asp-route-key="@accessKey.Key" data-bs-toggle="modal" data-bs-target="#ConfirmModal" data-description="This action will prevent <strong>@accessKey.Email</strong> from accessing this wallet." data-confirm-input="REMOVE">Remove</a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <p id="LNbank-AccessKeys" class="mt-4 text-secondary">There are no access keys yet.</p>
        }
    </div>
</div>

<partial name="_Confirm" model="@(new ConfirmModel("Remove access key", "This action will prevent the user from accessing this wallet. Are you sure?", "Remove"))" />

BTCPayServer.Plugins.LNbank/Pages/Wallets/Create.cshtml
@page "/plugins/lnbank/wallets/create"
@model BTCPayServer.Plugins.LNbank.Pages.Wallets.CreateModel

@{
    ViewData.SetActivePage(LNbankNavPages.Wallets, "Create a new LNbank wallet");
}

@section LNbankFoot {
    <partial name="_ValidationScriptsPartial" />
}

<partial name="_StatusMessage" />

<h2 class="mt-1 mb-4">@ViewData["Title"]</h2>

<div class="row">
    <div class="col-xl-8">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ReturnUrl" type="hidden" />
            <div class="form-group">
                <label asp-for="Wallet.Name" class="form-label"></label>
                <input asp-for="Wallet.Name" class="form-control" autofocus required />
                <span asp-validation-for="Wallet.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="LNbank-Create" />
            </div>
        </form>
    </div>
</div>

BTCPayServer.Plugins.LNbank/Pages/Wallets/Wallet.cshtml
@page "/plugins/lnbank/wallets/{walletId}"
@using BTCPayServer.Lightning
@using BTCPayServer.Plugins.LNbank.Data.Models
@inject BTCPayServer.Abstractions.Services.Safe Safe
@model BTCPayServer.Plugins.LNbank.Pages.Wallets.WalletModel

@{
    ViewData.SetActivePage(LNbankNavPages.Wallet, Model.Wallet.Name, Model.Wallet.WalletId);
    var pendingTransactionIds = Model.Transactions.Where(t => t.IsPending).Select(t => t.TransactionId);
}

@functions
{
    private string Tooltip(Transaction transaction)
    {
        var tt = transaction.IsSettled ? "" : "Awaiting settlement. ";
        if (transaction.HasRoutingFee) tt += $"Includes {Helpers.Millisats(transaction.RoutingFee)} routing fee.";
        return string.IsNullOrEmpty(tt) ? null : tt;
    }
}

<partial name="_WalletHeader" model="Model.Wallet"/>

@if (Model.Transactions.Any())
{
    <div class="row">
        <div class="col table-responsive-md">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="w-150px">
                        <div class="d-flex align-items-center gap-1">
                            Date
                            <button type="button" class="btn btn-link p-0 fa fa-clock-o switch-time-format" title="Switch date format"></button>
                        </div>
                    </th>
                    <th>Description</th>
                    <th class="text-end">Amount</th>
                    <th class="text-end">Settled</th>
                </tr>
                </thead>
                <tbody id="LNbank-WalletTransactions">
                @foreach (var transaction in Model.Transactions)
                {
                    <tr id="LNbank-Transaction-@transaction.TransactionId">
                        <td>
                            <a asp-page="/Transactions/Details" asp-route-walletId="@Model.Wallet.WalletId" asp-route-transactionId="@transaction.TransactionId" class="transaction-details">
                                @transaction.CreatedAt.ToBrowserDate(ViewsRazor.DateDisplayFormat.Relative)
                            </a>
                        </td>
                        <td>
                            <div class="d-inline-flex align-items-center gap-2">
                                <span class="transaction-description text-break">@transaction.Description</span>
                                <a asp-page="/Transactions/Edit" asp-route-walletId="@Model.Wallet.WalletId" asp-route-transactionId="@transaction.TransactionId" class="transaction-edit">
                                    Edit
                                </a>
                            </div>
                        </td>
                        <td class="text-nowrap text-end transaction-amount" data-amount="@transaction.Amount.ToUnit(LightMoneyUnit.MilliSatoshi)">
                            @Helpers.Sats(transaction.Amount)
                        </td>
                        <td class="text-nowrap text-end">
                            @if (transaction.IsPaid || transaction.IsSettled || transaction.IsPending)
                            {
                                <span class="text-@Helpers.TransactionStateClass(transaction) transaction-@(transaction.Status.ToLower())" data-amount-settled="@transaction.AmountSettled.ToUnit(LightMoneyUnit.MilliSatoshi)" data-transaction-fee="@transaction.RoutingFee?.ToUnit(LightMoneyUnit.MilliSatoshi)" data-bs-toggle="tooltip" data-bs-placement="left" title="@Tooltip(transaction)">
                                    @Helpers.Sats(transaction.AmountSettled)
                                </span>
                                @if (transaction.IsPending)
                                {
                                    <span class="text-@Helpers.TransactionStateClass(transaction) transaction-status">
                                        @transaction.Status
                                    </span>
                                }
                            }
                            else
                            {
                                <span class="text-@Helpers.TransactionStateClass(transaction) transaction-status">
                                    @transaction.Status
                                </span>
                            }
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
    
    @if (pendingTransactionIds.Any())
    {
        <script>
            (function () {
                const pending = @Safe.Json(pendingTransactionIds);
                window.LNbank.hubs.push({
                    id: 'transaction',
                    handlers: {
                        'transaction-update': data => {
                            if (pending.includes(data.transactionId)) {
                                window.location.reload();
                            }
                        }
                    }
                })
            })()
        </script>
    }
    
    <a class="btn btn-secondary dropdown-toggle mt-4 ms-auto" href="#" role="button" id="ExportDropdownToggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Export
    </a>
    <div class="dropdown-menu" aria-labelledby="ExportDropdownToggle">
        <a asp-controller="Export" asp-action="Export" asp-route-walletId="@Model.Wallet.WalletId" asp-route-format="csv" class="dropdown-item export-link" target="_blank">CSV</a>
        <a asp-controller="Export" asp-action="Export" asp-route-walletId="@Model.Wallet.WalletId" asp-route-format="json" class="dropdown-item export-link" target="_blank">JSON</a>
    </div>
}
else
{
    <p id="LNbank-WalletTransactions" class="text-secondary">There are no transactions yet.</p>
}

BTCPayServer.Plugins.LNbank/Pages/Wallets/_Nav.cshtml
@model BTCPayServer.Plugins.LNbank.Data.Models.Wallet

<nav id="SectionNav">
    <div class="nav">
        <a id="SectionNav-@(nameof(LNbankNavPages.WalletSettings))" class="nav-link @ViewData.IsActivePage(LNbankNavPages.WalletSettings, Model.WalletId)" asp-page="/Wallets/Details" asp-route-walletId="@Model.WalletId">General</a>
        <a id="SectionNav-@(nameof(LNbankNavPages.WalletAccessKeys))" class="nav-link @ViewData.IsActivePage(LNbankNavPages.WalletAccessKeys, Model.WalletId)" asp-page="/Wallets/AccessKeys" asp-route-walletId="@Model.WalletId">Access Keys</a>
    </div>
</nav>